### ISSUE TITLE
Deployment checklist for v0.7

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#1600]
- [x] Put organization status as active and reset the cache otherwise nothing will work
- [x] Clean all organization cache
- [x] Update stripe ids
- [x] check for Glific admin
- [x] Add customer.subscription.created on stripe portal

**Comment by pankaj-ag** [comment]
This is complete.
