### ISSUE TITLE
GraphQL docs for Glific API

### ISSUE THREAD

**Issue by dlobo** [glific/glific#193]
**Is your feature request related to a problem? Please describe.**
We need better documentation for our GraphQL API

**Describe the solution you'd like**
We will use [Slate](https://github.com/lord/slate#getting-started-with-slate). Please install locally

I have cloned the repository within [Glific](https://github.com/glific/slate). Use that version

**Tasks for this week**

- [x] Tags (Lobo)
- [x] Conversations (Lobo)
- [x] Groups (Lobo)
- [x] Contact Groups (Lobo)
- [x] Message Groups (Lobo)
- [x] Languages (Anshul)
- [x] Organizations (Anshul)
- [x] Providers (Anshul)
- [x] Contacts (Anshul)
- [x] Contacts Tags (Anshul)
- [x] Session Templates (Anshul)
- [x] Users (Anshul)
- [x] Users Groups (Anshul)
- [x] Registration (Anshul)
- [x] Messages (Pankaj)
- [x] Message Media (Pankaj)
- [x] Messages Tags (Pankaj)
- [x] Saved Searches (Pankaj)
- [x] Searches (Pankaj)
