### ISSUE TITLE
Project plan for CLAP v0.2 on Glific - KEF

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#2232]
Read all the requirements here. 
[Project plan for CLAP v0.2 on Glific - KEF](https://docs.google.com/document/d/1Ks2UPgMhm4_4w-_KM_jJQK4AKBy_U929onNAspumEKA)
There are three modules: 
1. Learning
2. Reports
3. Help
4. Dashboard

##  Learning: 

**Submodule:**  Worksheets
- [x] Load the current worksheets into the organization's data
- [x] Webhook to validate the worksheet code
- [x] Webhook to fetch the data for a worksheet based on code and update the flows
- [x] Update voice notes
- [x] Convert reflection questions to interactive messages
- [x]  GCS bucket structure.  Folder hierarchy: school id > phone numbers > files
- [x] Validate school id and school name

**Submodule:**  Helping Hand
- [x] Mark with video activity as completed. 
- [ ] Allow the KEF team to update the total video counter when they add a new topic.

## Reports: 
- [x] Add labels to the worksheet and help hands flow to get the report's data.
- [x] Webhook to generate the report's message

## Dashboard: 
- [x] Add labels to all the flows to get the [desired dashboard.](https://docs.google.com/drawings/d/1byptBMETrEvc1TXPO0r0EBJCTwxFtpBeAqUXLGags8E/edit)
- [ ] Write Queries and build graphs on Data studio
