### ISSUE TITLE
Automated Flow Tester

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific#3235]
**Is your feature request related to a problem? Please describe.**
The design & logical errors during flow creation is a major issue that happens across all NGOs. The ability to mitigate the errors or help them troubleshoot the issues at a Publishing level would be really helpful. Currently, we've a set of errors which are shown at the time of publishing. This feature is an enhancement to the existing functionality to alert the NGOs about more design flaws which is not handled currently.

**Describe the solution you'd like**

- [x] glific/glific#3241
- [x] glific/glific-frontend#2632
- [ ] glific/glific-frontend#2630
- [x] glific/glific#3223
- [x] glific/glific-frontend#2645
- [x] glific/glific#3227
- [x] glific/glific#3228
- [x] glific/glific-frontend#2633
- [x] glific/glific#3230
- [x] glific/glific#3231
- [x] #3240
- [x] https://github.com/glific/glific/issues/3250
- [ ] https://github.com/glific/glific/issues/3258

**Additional context**
The NGOs which encountered some of the issues are also mentioned along with each issue

**Comment by aravind-glific** [comment]
Design Link : https://www.figma.com/proto/hvzGlCIQBSwHQ70bsW5m9Z/Web-app?page-id=2%3A2649&type=design&node-id=2102-3020&viewport=-4327%2C-9927%2C0.32&t=p1HdoGl9quCLd3y2-1&scaling=min-zoom

**Comment by AkhileshNegi** [comment]
Majority of issues have been closed, while the remaining will take care in some time
