### ISSUE TITLE
WA Groups v2: Master issue

### ISSUE THREAD

**Issue by madclaws** [glific/glific#3881]
Here are the issues we will be working on for WA groups v2

- [x] https://github.com/glific/glific/issues/3831
    - [x] https://github.com/glific/glific/issues/3891
    - [x] https://github.com/glific/glific/issues/3892
- [x] https://github.com/glific/glific/issues/3877
- [x] https://github.com/glific/glific/issues/3879
- [x] https://github.com/glific/glific/issues/3878
- [x] https://github.com/glific/glific/issues/3882
- [x] https://github.com/glific/glific/issues/3959
- [x] https://github.com/glific/glific/issues/3960
- [x] https://github.com/glific/glific/issues/3873
- [x] https://github.com/glific/glific/issues/3963
- [x] https://github.com/glific/glific/issues/4038
- [x] https://github.com/glific/glific/issues/3582
